"""Add EEBO-TCP fields to Work model

Revision ID: 032e46300d4c
Revises: 9c48e02f534a
Create Date: 2024-12-07 22:24:21.225140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032e46300d4c'
down_revision = '9c48e02f534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tcp_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('eebo_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_library', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('collection', sa.String(length=50), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_index('idx_tcp_id', ['tcp_id'], unique=False)
        batch_op.create_index('idx_title', ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_tcp_id'), ['tcp_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_tcp_id'))
        batch_op.drop_index('idx_title')
        batch_op.drop_index('idx_tcp_id')
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('collection')
        batch_op.drop_column('language')
        batch_op.drop_column('source_library')
        batch_op.drop_column('vid')
        batch_op.drop_column('eebo_id')
        batch_op.drop_column('tcp_id')

    # ### end Alembic commands ###
