"""Add Oauth fields

Revision ID: 079d1d6cf1ae
Revises: 3883575dce23
Create Date: 2024-12-05 19:23:22.826799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079d1d6cf1ae'
down_revision = '3883575dce23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('oauth_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('oauth_avatar', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('unique_oauth_user', ['oauth_provider', 'oauth_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_oauth_user', type_='unique')
        batch_op.drop_column('oauth_avatar')
        batch_op.drop_column('oauth_username')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
